import type { Metadata } from 'next';

import './globals.css';
import { Footer } from '@/widgets/footer';
import { Header } from '@/widgets/header';
import { NavigationBar } from '@/widgets/navigation-bar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header>
          <NavigationBar />
        </Header>
        {children}
        <Footer />
      </body>
    </html>
  );
}
